# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Spotify-list' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotify-list
  pod 'Alamofire', '~> 4.4'

  target 'Spotify-listTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Spotify-listUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
