# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Alamofire teste' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alamofire teste
  pod 'Alamofire', '~> 4.4'
end
